package constants

const (
	RouteHealth                = "/health"
	RouteAPIV1Prefix           = "/api/v1"
	RouteSlackChannelCreate    = "/slack/channel/create"
	RouteSlackAddMember        = "/slack/member/add"
	RouteSlackGetAllUsers      = "/slack/users/all"
	RouteSlackGetAllChannels   = "/slack/channels/all"
	RouteSlackGetUserByName    = "/slack/user/by-name"
	RouteSlackGetUserByID      = "/slack/user/by-id"
	RouteSlackGetChannelByName = "/slack/channel/by-name"
	RouteSlackGetChannelByID   = "/slack/channel/by-id"
	RouteSlackSendMessage      = "/slack/message/send"
	RouteApprovalGetAll        = "/approval/all"
	RouteApprovalGetPending    = "/approval/pending"
	RouteApprovalGetByID       = "/approval/by-id"
	RouteApprovalCreate        = "/approval/request"

	ErrorInvalidRequestBody       = "Invalid request body"
	ErrorChannelNameRequired      = "channel_name is required"
	ErrorChannelIDRequired        = "channel_id is required"
	ErrorUserNameRequired         = "user_name is required"
	ErrorUserIDRequired           = "user_id is required"
	ErrorChannelCreationFailed    = "failed to create channel"
	ErrorTopicSetFailed           = "Failed to set channel description"
	ErrorAddMemberFailed          = "failed to add member to channel"
	ErrorGetUsersFailed           = "failed to get users"
	ErrorGetChannelsFailed        = "failed to get channels"
	ErrorUserNotFound             = "user not found"
	ErrorChannelNotFound          = "channel not found"
	ErrorSlackTokenRequired       = "SLACK_BOT_TOKEN is required"
	ErrorAppTokenRequired         = "SLACK_APP_TOKEN is required"
	ErrorApprovalNotFound         = "approval request not found"
	ErrorApprovalAlreadyProcessed = "approval already processed"

	SuccessChannelCreated    = "Channel created successfully"
	SuccessMemberAdded       = "Member added successfully"
	SuccessUsersFetched      = "Users fetched successfully"
	SuccessChannelsFetched   = "Channels fetched successfully"
	SuccessUserFetched       = "User fetched successfully"
	SuccessChannelFetched    = "Channel fetched successfully"
	SuccessMessageSent       = "Message sent successfully"
	SuccessApprovalProcessed = "Approval processed successfully"

	EnvServiceName   = "SERVICE_NAME"
	EnvServicePort   = "SERVICE_PORT"
	EnvServiceHost   = "SERVICE_HOST"
	EnvSlackBotToken = "SLACK_BOT_TOKEN"
	EnvSlackAppToken = "SLACK_APP_TOKEN"
	EnvLogLevel      = "LOG_LEVEL"
	EnvEnvironment   = "ENVIRONMENT"
	EnvKafkaBrokers  = "KAFKA_BROKERS"
	EnvKafkaGroupID  = "KAFKA_GROUP_ID"

	DefaultServiceName  = "approval-service"
	DefaultServicePort  = "8083"
	DefaultServiceHost  = "0.0.0.0"
	DefaultLogLevel     = "debug"
	DefaultEnvironment  = "development"
	DefaultKafkaBrokers = "localhost:9092"
	DefaultKafkaGroupID = "approval-service-group"

	HealthStatusKey    = "status"
	HealthStatusValue  = "healthy"
	HealthServiceKey   = "service"
	HealthServiceValue = "approval-service"

	LogLevelDebug   = "debug"
	LogLevelRelease = "release"

	ErrorMessageSendFailed   = "failed to send message"
	ErrorMessageTextRequired = "message text is required"
	ErrorInvalidMentionType  = "invalid mention type"

	MentionTypeUser          = "user"
	MentionTypeUserByName    = "user_by_name"
	MentionTypeChannelLink   = "channel_link"
	MentionTypeChannelByName = "channel_by_name"
	MentionTypeHere          = "here"
	MentionTypeChannelNotify = "channel"
	MentionTypeEveryone      = "everyone"
	MentionTypeUserGroup     = "usergroup"

	DBPath = "approval_service.db"

	ApprovalStatusPending  = "pending"
	ApprovalStatusApproved = "approved"
	ApprovalStatusRejected = "rejected"

	KafkaTopicApprovalRequested = "approval.requested"
	KafkaTopicApprovalCompleted = "approval.completed"

	ActionApprove = "approve_request"
	ActionReject  = "reject_request"
)
