package constants

const (
	RouteHealth                  = "/health"
	RouteAPIV1Prefix             = "/api/v1"
	RouteSlackChannelCreate      = "/slack/channel/create"
	RouteSlackAddMember          = "/slack/member/add"
	RouteSlackGetAllUsers        = "/slack/users/all"
	RouteSlackGetAllChannels     = "/slack/channels/all"
	RouteSlackGetUserByName      = "/slack/user/by-name"
	RouteSlackGetUserByID        = "/slack/user/by-id"
	RouteSlackGetChannelByName   = "/slack/channel/by-name"
	RouteSlackGetChannelByID     = "/slack/channel/by-id"
	RouteSlackSendMessage        = "/slack/message/send"
	RouteSlackSendApprovalButton = "/slack/approval-form-button/send"
	RouteApprovalGetAll          = "/approval/all"
	RouteApprovalGetPending      = "/approval/pending"
	RouteApprovalGetByID         = "/approval/by-id"
	RouteApprovalCreate          = "/approval/request"

	ErrorInvalidRequestBody       = "Invalid request body"
	ErrorChannelNameRequired      = "channel_name is required"
	ErrorChannelIDRequired        = "channel_id is required"
	ErrorUserNameRequired         = "user_name is required"
	ErrorUserIDRequired           = "user_id is required"
	ErrorChannelCreationFailed    = "failed to create channel"
	ErrorTopicSetFailed           = "Failed to set channel description"
	ErrorAddMemberFailed          = "failed to add member to channel"
	ErrorGetUsersFailed           = "failed to get users"
	ErrorGetChannelsFailed        = "failed to get channels"
	ErrorUserNotFound             = "user not found"
	ErrorChannelNotFound          = "channel not found"
	ErrorSlackTokenRequired       = "SLACK_BOT_TOKEN is required"
	ErrorAppTokenRequired         = "SLACK_APP_TOKEN is required"
	ErrorApprovalNotFound         = "approval request not found"
	ErrorApprovalAlreadyProcessed = "approval already processed"

	SuccessChannelCreated    = "Channel created successfully"
	SuccessMemberAdded       = "Member added successfully"
	SuccessUsersFetched      = "Users fetched successfully"
	SuccessChannelsFetched   = "Channels fetched successfully"
	SuccessUserFetched       = "User fetched successfully"
	SuccessChannelFetched    = "Channel fetched successfully"
	SuccessMessageSent       = "Message sent successfully"
	SuccessApprovalProcessed = "Approval processed successfully"

	EnvServiceName   = "SERVICE_NAME"
	EnvServicePort   = "SERVICE_PORT"
	EnvServiceHost   = "SERVICE_HOST"
	EnvSlackBotToken = "SLACK_BOT_TOKEN"
	EnvSlackAppToken = "SLACK_APP_TOKEN"
	EnvLogLevel      = "LOG_LEVEL"
	EnvEnvironment   = "ENVIRONMENT"
	EnvKafkaBrokers  = "KAFKA_BROKERS"
	EnvKafkaGroupID  = "KAFKA_GROUP_ID"

	DefaultServiceName  = "approval-service"
	DefaultServicePort  = "8083"
	DefaultServiceHost  = "0.0.0.0"
	DefaultLogLevel     = "debug"
	DefaultEnvironment  = "development"
	DefaultKafkaBrokers = "localhost:9092"
	DefaultKafkaGroupID = "approval-service-group"

	HealthStatusKey    = "status"
	HealthStatusValue  = "healthy"
	HealthServiceKey   = "service"
	HealthServiceValue = "approval-service"

	LogLevelDebug   = "debug"
	LogLevelRelease = "release"

	ErrorMessageSendFailed   = "failed to send message"
	ErrorMessageTextRequired = "message text is required"
	ErrorInvalidMentionType  = "invalid mention type"

	MentionTypeUser          = "user"
	MentionTypeUserByName    = "user_by_name"
	MentionTypeChannelLink   = "channel_link"
	MentionTypeChannelByName = "channel_by_name"
	MentionTypeHere          = "here"
	MentionTypeChannelNotify = "channel"
	MentionTypeEveryone      = "everyone"
	MentionTypeUserGroup     = "usergroup"

	DBPath = "approval_service.db"

	ApprovalStatusPending  = "pending"
	ApprovalStatusApproved = "approved"
	ApprovalStatusRejected = "rejected"

	KafkaTopicApprovalRequested = "approval.requested"
	KafkaTopicApprovalCompleted = "approval.completed"
	KafkaTopicActionExecuted    = "action.executed"
	KafkaTopicActionRejected    = "action.rejected"

	ActionApprove          = "approve_request"
	ActionReject           = "reject_request"
	ActionOpenApprovalForm = "open_approval_form"

	ModalCallbackApprove    = "approval_modal_approve"
	ModalCallbackReject     = "approval_modal_reject"
	InputBlockComment       = "comment_input_block"
	InputActionComment      = "comment_input_action"
	CommentMaxLength        = 500
	ErrorCommentRequired    = "Comment is required for rejection"
	ModalTitleApprove       = "Approve Request"
	ModalTitleReject        = "Reject Request"
	ModalSubmitApprove      = "Approve"
	ModalSubmitReject       = "Reject"
	ModalLabelComment       = "Reason/Comment"
	ModalPlaceholderApprove = "Enter your approval reason (optional)"
	ModalPlaceholderReject  = "Enter your rejection reason (required)"

	RouteSlackSlashCommand = "/slack/slash-command"

	SlashCommandApprovalRequest = "/approval-request"

	ModalCallbackCreateApproval = "create_approval_modal"

	InputBlockTitle        = "title_input_block"
	InputActionTitle       = "title_input_action"
	InputBlockDescription  = "description_input_block"
	InputActionDescription = "description_input_action"
	InputBlockApprover     = "approver_input_block"
	InputActionApprover    = "approver_input_action"
	InputBlockPriority     = "priority_input_block"
	InputActionPriority    = "priority_input_action"
	InputBlockCategory     = "category_input_block"
	InputActionCategory    = "category_input_action"
	InputBlockAttachments  = "attachments_input_block"
	InputActionAttachments = "attachments_input_action"
	InputBlockDueDate      = "due_date_input_block"
	InputActionDueDate     = "due_date_input_action"

	ModalTitleCreateApproval    = "Create Approval Request"
	ModalSubmitCreateApproval   = "Submit Request"
	ModalLabelTitle             = "Request Title"
	ModalPlaceholderTitle       = "Enter a brief title for your request"
	ModalLabelDescription       = "Description"
	ModalPlaceholderDescription = "Provide detailed information about your request"
	ModalLabelApprover          = "Select Approver"
	ModalPlaceholderApprover    = "Choose who should approve this"
	ModalLabelPriority          = "Priority Level"
	ModalLabelCategory          = "Category"
	ModalPlaceholderCategory    = "Select request category"
	ModalLabelAttachments       = "Attachments/Links"
	ModalPlaceholderAttachments = "Add URLs or file links (optional)"
	ModalLabelDueDate           = "Due Date"
	ModalPlaceholderDueDate     = "Select when this needs approval"

	PriorityLow    = "low"
	PriorityMedium = "medium"
	PriorityHigh   = "high"
	PriorityUrgent = "urgent"

	CategoryCodeChange     = "code_change"
	CategoryMergeRequest   = "merge_request"
	CategoryDeployment     = "deployment"
	CategoryAccess         = "access"
	CategoryInfrastructure = "infrastructure"
	CategoryOther          = "other"

	TitleMaxLength       = 100
	DescriptionMaxLength = 1000
	AttachmentsMaxLength = 500

	ErrorTitleRequired       = "Title is required"
	ErrorDescriptionRequired = "Description is required"
	ErrorApproverRequired    = "Approver is required"
	ErrorPriorityRequired    = "Priority is required"
	ErrorCategoryRequired    = "Category is required"

	RouteApprovalDomainChange = "/approval/domain-change"
	RouteSlackGetDMChannel    = "/slack/dm-channel/get"
	RouteSlackGetAllApps      = "/slack/apps/all"

	MessageDestinationChannel = "channel"
	MessageDestinationAppDM   = "app_dm"
)
